project_id = "hkqifrhpwehknawpcspg"

[functions.fetch-currency-rates]
verify_jwt = false

[functions.fetch-news]
verify_jwt = false

[functions.fetch-global-indices]
verify_jwt = false

[functions.fetch-asset-quotes]
verify_jwt = false

[functions.fetch-stocks]
verify_jwt = false

[functions.fetch-market-correlations]
verify_jwt = false

[functions.analyze-daily-correlations]
verify_jwt = false

[functions.gex-api]
verify_jwt = false
